<?php 
return [
	'type'=>'mysql',
	'hostname'=>'127.0.0.1',
	'database'=>'hanse_cms',
	'username'=>'root',
	'password'=>'root',
	'hostport'=>'',
	'dsn'=>'',
	'params'=>[],
	'charset'=>'utf8',
	'prefix'=>'cms_',
	'debug'=>'1',
	'deploy'=>'0',
	'rw_separate'=>'',
	'master_num'=>'1',
	'slave_no'=>'',
	'read_master'=>'',
	'fields_strict'=>'1',
	'resultset_type'=>'array',
	'auto_timestamp'=>'',
	'datetime_format'=>'Y-m-d H:i:s',
	'sql_explain'=>'',
];
